### ISSUE TITLE
Hot Reloading with State

### ISSUE THREAD

**Issue by aaronplanell** [aaronplanell/todolist-react-redux-wcra#1]
Hi!

I have a very interesting problem. I migrated my old [Todo with React&Redux Project](https://github.com/aaronplanell/todolist-react-redux) to a new one that uses [Create-React-App](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html). The problem is that I have time travelling :smile: , but I loss the state in every hot reloading event :fearful: .

Maybe @gaearon knows how to fix it :+1:

**Comment by aaronplanell** [comment]
Ooops! I downloaded the [ToDo Example](https://github.com/reactjs/redux/tree/master/examples/todos) of @gaearon that currently works with [Create-React-App](https://github.com/aaronplanell/todolist-react-redux) and it has the same issue. It loss the state :cry:

**Comment by aaronplanell** [comment]
**Step 1:**
- Download and execute the redux todo example:

```
git clone https://github.com/reactjs/redux.git
cd redux/examples/todo
npm install
npm start
```

**Step 2:**
- Open http://localhost:3000/
- Insert a Todo

**Step 3:**
- Edit redux/examples/todos/src/components/Footer.js
- Change 'All' (line 9) for 'All items'
- Save

The state will be loss.

**Comment by aaronplanell** [comment]
Add these lines at the index.js file:

```
//Adding Hot Module Reloading to Create React App
if (module.hot) {
  module.hot.accept(Provider, () => {
    const NextApp = Provider.default;
    render(
      <NextApp />,
      root
    );
  });
}
```

**Comment by gaearon** [comment]
No, this is not right.

You don't need need to "accept" Provider because it is not your code :-). You need to "accept" _your_ root component because that's the code that changes. 

I recommend reading about HMR before using it because this is not how it's supposed to be used, and will not work.

**Comment by aaronplanell** [comment]
Hi @gaearon !

It's very strange. With: 

```
  module.hot.accept(Provider, () => {
    const NextApp = Provider.default;
```

Works fine.

Also, I changed it for using HMR with the App Component, as you said in the previous post, and works too. The final code is this:

```
//Adding Hot Module Reloading to Create React App
if (module.hot) {
  module.hot.accept(App, () => {
    const NextApp = App.default;
    render(
      <NextApp />,
      root
    );
  });
}
```

Thanks a lot for your help!!! :+1:

**Comment by aaronplanell** [comment]
Reading this info: https://github.com/reactjs/react-redux/releases/tag/v2.0.0

**Comment by gaearon** [comment]
No, this is not right either.

Please read about hot module replacement API. You seem to be copying these snippets without understanding what they do. If it works, it only works by accident (and is likely broken in some way).

The code should look like this:

``` js
// ...

import App from './App';

// ...

render(
  <Provider store={store} >
    <App />
  </Provider>,
  root
);

if (module.hot) {
  // First argument is filename. Not the App class :-)
  // Wrong:
  // module.hot.accept(App, () => {
  // Right:
  module.hot.accept('./App', () => {
    // Just reading App.default will give you the previous version.
    // You want to `require()` it again to get the next version.
    // Wrong:
    // const NextApp = App.default;
    // Right:
    const NextApp = require('./App').default;
    render(
      // You want to render the exact same thing you rendered previously,
      // but with new <App />. Previously you put it inside a <Provider>
      // so you also need to do that here.
      // Wrong:
      // <NextApp />,
      // Right:
      <Provider store={store}>
        <NextApp />
      </Provider>,
      root
    );
  });
```

**Comment by aaronplanell** [comment]
Thanks a lot @gaearon !!! I fixed it with your solution :+1: 
I think that you must be one of the most patient men in the world, hehehe :smile:

**Comment by gaearon** [comment]
It would be simpler btw if Provider was already rendered as part of the App. Then you could omit it here.
